title: DNF78 Jekyll Blog Space
author: DNF78
email: DNF78 via GitHub
description: > # this means to ignore newlines until "baseurl:"
 This is to be a simple blog as I learn about the jekyll editor and Github pages

# social links
twitter_username: Github # DO NOT include the @ character, or else the build will fail!
github_username:  DNF78 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

#remote_theme: pages-themes/merlot@v0.2.0
#plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
